### ISSUE TITLE
Say2

### ISSUE THREAD

**Issue by w3nder** [nartallax/gaming#3]

**Comment by WeenderT** [comment]
```
	writeByte(writer, 0x38);
	writeAsciiAsUtf16(writer, message, sizeof(message));
	writeInt(writer, jsonValueByKey(obj, "type_msg")->u.integer);
```

I was able to send message via l2cli.
Could you just tell me how to send a message other than just the global one. passing a different type_msg?

I got a lot of information reading the javascript from another project 

38 74 00 65 00 73 00 74 00 65 00 00 00 01 00 00 00 // Type 1
38 74 00 65 00 73 00 74 00 65 00 00 00 00 00 00 00  // Type 0
Message: teste
`{"type":"Say2","message":"teste", "type_msg": 1}\n`
```
{
  type: 'Say2',
  objId: 1227903765,
  messageType: 'General',
  source: 'ItsJoel12',
  message: 'teste'
}
```
