### ISSUE TITLE
JoinParty

### ISSUE THREAD

**Issue by w3nder** [nartallax/gaming#4]

**Comment by nartallax** [comment]
Not really, as long as you didn't even provided callstack of segfault.

But there is something to think about:

1. writeString writes the string of fixed length and fills unoccupied length with zeroes. My datasheet (from docs directory) is unclear about this package layout; maybe it's arbitrary length string?
2. If you're trying to write this exact package, you have way too many calls of writeShort and writeInt. Only one call will be sufficient - writeInt(writer, 4)
In my datasheet, there is only one int after nickname string, which holds the value for loot distribution.

Keep in mind that I didn't touched this project for a while, and probably forgot something.

**Comment by SunTzux** [comment]
fixed

```
void encodeRequestJoinParty(json_value *obj, Binwriter *writer)
{
	json_value* nick = jsonValueByKey(obj, "nick");
	char* nick = nick->u.string.ptr;
	int nickLength = nick->u.string.length;

	writeByte(writer, 0x29);
	writeAsciiAsUtf16(writer, nick, nickLength);
	writeInt(writer, 0);
	writeInt(writer, 0);
	writeInt(writer, 1);
	writeInt(writer, 0);
	writeInt(writer, 0);
	writeInt(writer, 0);
}
```

I was misread the nick.
